m1_user:
    resource: "@M1UserBundle/Controller/"
    type:     annotation
    prefix:   /

m1_mag_app:
    resource: "@M1MagAppBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: '@AppBundle/Controller/'
    type: annotation


