m1_mag_app_homepage:
    path:     /
    defaults: { _controller: M1MagAppBundle:Produit:index }
    
m1_mag_app_detailpage:
    path:     /detail/{ref}
    defaults: { _controller: M1MagAppBundle:Produit:detail }



add_prod:
    path: /Magasinier/Ajout_Produit
    defaults: {_controller: M1MagAppBundle:Produit:add}  


add_categorie:
    path: /Magasinier/ajout_Categorie
    defaults: {_controller: M1MagAppBundle:Categorie:add}  

saved_categorie:
    path: /Magasinier/Save_Cat
    defaults: {_controller: M1MagAppBundle:Categorie:add}  

list_stock:
    path: /Magasinier/stock
    defaults: {_controller: M1MagAppBundle:Produit:listStock}  

update_stock:
    path: /Magasinier/setStock/{id}
    defaults: {_controller: M1MagAppBundle:Produit:updateStock}  

list_panier:
    path: /Magasinier/panier
    defaults: {_controller: M1MagAppBundle:Panier:listPanier}  

valide_panier:
    path: /Magasinier/validePanier/{id}
    defaults: {_controller: M1MagAppBundle:Panier:validerPanier}  

details_panier:
    path: /Magasinier/detailsPanier/{id}
    defaults: {_controller: M1MagAppBundle:Panier:detailsPanier}  

