m1_mag_app_homepage:
    path:     /
    defaults: { _controller: M1MagAppBundle:Produit:index }
    
m1_mag_app_detailpage:
    path:     /detail/{ref}
    defaults: { _controller: M1MagAppBundle:Produit:detail }

m1_mag_app_voirPanierpage:
    path:     /MonPanier
    defaults: { _controller: M1MagAppBundle:Produit:voirmonpanier }

m1_mag_app_choixadressepage:
    path:     /choixadresse
    defaults: { _controller: M1MagAppBundle:Adresse:choixadresse }

m1_mag_app_panieradressepage:
    path:     /Panier/adresse/{refadresse}
    defaults: { _controller: M1MagAppBundle:Panier:enregistreadresse }

m1_mag_app_addadressepage:
    path:     /addadresse
    defaults: { _controller: M1MagAppBundle:Adresse:addadresse }

m1_mag_app_validerpanierpage:
    path:     /Panier/valider
    defaults: { _controller: M1MagAppBundle:Panier:valide }

m1_mag_app_listecommandepage:
    path:     /ListeCommandes
    defaults: { _controller: M1MagAppBundle:Commande:liste }

add_prod:
    path: /Magasinier/Ajout_Produit
    defaults: {_controller: M1MagAppBundle:Produit:add}  


add_categorie:
    path: /Magasinier/ajout_Categorie
    defaults: {_controller: M1MagAppBundle:Categorie:add}  

saved_categorie:
    path: /Magasinier/Save_Cat
    defaults: {_controller: M1MagAppBundle:Categorie:add}  

list_stock:
    path: /Magasinier/stock
    defaults: {_controller: M1MagAppBundle:Produit:listStock}  

update_stock:
    path: /Magasinier/setStock/{id}
    defaults: {_controller: M1MagAppBundle:Produit:updateStock}  

list_panier:
    path: /Magasinier/panier
    defaults: {_controller: M1MagAppBundle:Panier:listPanier}  

valide_panier:
    path: /Magasinier/validePanier/{id}
    defaults: {_controller: M1MagAppBundle:Panier:validerPanier}  

details_panier:
    path: /Magasinier/listCommande/{id}
    defaults: {_controller: M1MagAppBundle:Commande:listCommande}  

