<?php

namespace M1\MagAppBundle\Repository;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllCategories()
  {
    return $this->createQueryBuilder('p');
  }

}
