<?php

namespace M1\MagAppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * PaniersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaniersRepository extends \Doctrine\ORM\EntityRepository
{

	public function findPanierValider()
	{
        $qb = $this->createQueryBuilder('p');

        $qb->where('p.etat = :etat')->setParameter('etat', 'valide');

       return $qb->getQuery()->getResult();
   }

}
