<?php

namespace M1\MagAppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
	public function findProduit($id)
	{
        $query = $this->createQueryBuilder('p');

        $query->where('p.id = :id')->setParameter('id', $id);

       return $query->getQuery()->getResult();
   }
}
