<?php

namespace M1\MagAppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
	/*public function findProduit($id)
	{
        $query = $this->createQueryBuilder('p');

        $query->where('p.id = :id')->setParameter('id', $id);

       return $query->getQuery()->getResult();
   }*/

   public function findProduitByParametres($data)
   {
   		$query = $this->createQueryBuilder('p');
		$query->where('p.nom LIKE  :nom')
		->andWhere('p.reference LIKE  :reference ')
		->setParameters(array( 'nom' => '%'.$data['name'].'%',  'reference' => '%'.$data['ref'].'%'));

    return $query->getQuery()->getResult();
   }

}
