<?php

namespace M1\MagAppBundle\Repository;

/**
 * VentesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentesRepository extends \Doctrine\ORM\EntityRepository
{

	public function findCommandes($panier)
	{
        $qb = $this->createQueryBuilder('c');

        $qb->where('c.panier = :panier')->setParameter('panier', $panier);

       return $qb->getQuery()->getResult();
   }
}
